site_name: tinakoziol.com
site_description: Personal website of Dr Tina Koziol
docs_dir: docs
repo_url: "https://github.com/t1nak/"
# Configuration
theme:
  name: material
  palette:
    primary: indigo #blue grey

  features:
    - navigation.tabs 
  language: en
# Page tree
nav:
  - Home: index.md
  - Miscellaneous - Debate and Misinformation: debate.md
  - CV: cv.md

  - Research: 
    - Work in progress: research.md
  - Python for Economists: 
    - Why learn python: python.md
    
        - Download and analyse SARB BA900 forms: blog/2020/ba900-download.md
        - Catalina and conda: blog/2020/Catalinaconda.md
        - Install python: blog/2020/installpy.md

extra_css:
    - css/extra.css

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto